name: Auto Make Zip
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          zip -r app-v${{ github.run_number }}.zip. -x "*.git*" "*.github*"
          echo '{"version": ${{ github.run_number }}, "zip_url": "https://jithinrajrk147-glitch.github.io/Anxro/app-v${{ github.run_number }}.zip"}' > app-version.json
          git config user.name github-actions
          git config user.email actions@github.com
          git add.
          git commit -m "auto release v${{ github.run_number }}" || true
          git push
